<html>
    <head>
        <title> login </title>
        <link rel="stylesheet" type = "text/css" href = "../css/login.css">
    </head>
    <body>
        <h2>Camagru</h2>
        <div class="login-box">
            <img src="../avatar.png" class="avatar">
            <h1>Login</h1>
            <form name="login" action="../php/login.php" method="POST">
                <p>Username</p>
                <input type="text" name="username" placeholder="Enter Username">
                <p>Password</p>
                <input type="password" name="password" placeholder="Enter Password">
                <input type="submit" name="login" value="Login">
                <a href="../html/forgotpass.html">Forgot Password?</a><br>
                <a href="signup.html">Sign Up?</a>
            </form>
        </div>
    </body>
</html>